-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FFT_DIT_RN is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_r_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    in_r_empty_n : IN STD_LOGIC;
    in_r_read : OUT STD_LOGIC;
    out_r_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    out_r_full_n : IN STD_LOGIC;
    out_r_write : OUT STD_LOGIC );
end;


architecture behav of FFT_DIT_RN is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "FFT_DIT_RN_FFT_DIT_RN,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.091000,HLS_SYN_LAT=1258,HLS_SYN_TPT=none,HLS_SYN_MEM=123,HLS_SYN_DSP=0,HLS_SYN_FF=79998,HLS_SYN_LUT=65078,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal revIdxTab_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal revIdxTab_ce0 : STD_LOGIC;
    signal revIdxTab_we0 : STD_LOGIC;
    signal revIdxTab_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0 : STD_LOGIC;
    signal FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FFT_pipeline_DIT_fu_154_in_r_read : STD_LOGIC;
    signal grp_FFT_pipeline_DIT_fu_154_mid_din : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_FFT_pipeline_DIT_fu_154_mid_write : STD_LOGIC;
    signal grp_FFT_pipeline_DIT_fu_154_revIdxTab_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_FFT_pipeline_DIT_fu_154_revIdxTab_ce0 : STD_LOGIC;
    signal grp_FFT_pipeline_DIT_fu_154_revIdxTab_d0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_FFT_pipeline_DIT_fu_154_revIdxTab_we0 : STD_LOGIC;
    signal grp_FFT_pipeline_DIT_fu_154_revIdxTab_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_FFT_pipeline_DIT_fu_154_revIdxTab_ce1 : STD_LOGIC;
    signal grp_FFT_pipeline_DIT_fu_154_revIdxTab_d1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_FFT_pipeline_DIT_fu_154_revIdxTab_we1 : STD_LOGIC;
    signal grp_FFT_pipeline_DIT_fu_154_ap_start : STD_LOGIC;
    signal grp_FFT_pipeline_DIT_fu_154_ap_done : STD_LOGIC;
    signal grp_FFT_pipeline_DIT_fu_154_ap_ready : STD_LOGIC;
    signal grp_FFT_pipeline_DIT_fu_154_ap_idle : STD_LOGIC;
    signal grp_FFT_pipeline_DIT_fu_154_ap_continue : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_done : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_idle : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_ready : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_mid_read : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_done : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_idle : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_ready : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_idle : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_ready : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_din : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_write : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 : STD_LOGIC;
    signal grp_FFT_pipeline_DIT_fu_154_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done : STD_LOGIC := '0';
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_sync_grp_FFT_pipeline_DIT_fu_154_ap_ready : STD_LOGIC;
    signal mid_full_n : STD_LOGIC;
    signal mid_write : STD_LOGIC;
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal mid_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal mid_empty_n : STD_LOGIC;
    signal mid_read : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg : STD_LOGIC := '0';
    signal grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component FFT_DIT_RN_FFT_pipeline_DIT IS
    port (
        in_r_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        in_r_empty_n : IN STD_LOGIC;
        in_r_read : OUT STD_LOGIC;
        mid_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        mid_full_n : IN STD_LOGIC;
        mid_write : OUT STD_LOGIC;
        revIdxTab_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        revIdxTab_ce0 : OUT STD_LOGIC;
        revIdxTab_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        revIdxTab_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
        revIdxTab_we0 : OUT STD_LOGIC;
        revIdxTab_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        revIdxTab_ce1 : OUT STD_LOGIC;
        revIdxTab_d1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        revIdxTab_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
        revIdxTab_we1 : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component FFT_DIT_RN_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mid_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        mid_empty_n : IN STD_LOGIC;
        mid_read : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FFT_DIT_RN_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        revIdxTab_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        revIdxTab_ce0 : OUT STD_LOGIC;
        revIdxTab_q0 : IN STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component FFT_DIT_RN_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_r_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        out_r_full_n : IN STD_LOGIC;
        out_r_write : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 : OUT STD_LOGIC;
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FFT_DIT_RN_revIdxTab_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (6 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FFT_DIT_RN_fifo_w256_d8_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (255 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (255 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    revIdxTab_U : component FFT_DIT_RN_revIdxTab_RAM_AUTO_1R1W
    generic map (
        DataWidth => 7,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => revIdxTab_address0,
        ce0 => revIdxTab_ce0,
        we0 => revIdxTab_we0,
        d0 => grp_FFT_pipeline_DIT_fu_154_revIdxTab_d0,
        q0 => revIdxTab_q0);

    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_U : component FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0,
        ce0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0,
        we0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0,
        d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_d0,
        q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_q0);

    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_U : component FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0,
        ce0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0,
        we0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0,
        d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_d0,
        q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_q0);

    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_U : component FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0,
        ce0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0,
        we0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0,
        d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_d0,
        q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_q0);

    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_U : component FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0,
        ce0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0,
        we0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0,
        d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_d0,
        q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_q0);

    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_U : component FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0,
        ce0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0,
        we0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0,
        d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_d0,
        q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_q0);

    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_U : component FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0,
        ce0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0,
        we0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0,
        d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_d0,
        q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_q0);

    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_U : component FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0,
        ce0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0,
        we0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0,
        d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_d0,
        q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_q0);

    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_U : component FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0,
        ce0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0,
        we0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0,
        d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_d0,
        q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_q0);

    grp_FFT_pipeline_DIT_fu_154 : component FFT_DIT_RN_FFT_pipeline_DIT
    port map (
        in_r_dout => in_r_dout,
        in_r_empty_n => in_r_empty_n,
        in_r_read => grp_FFT_pipeline_DIT_fu_154_in_r_read,
        mid_din => grp_FFT_pipeline_DIT_fu_154_mid_din,
        mid_full_n => mid_full_n,
        mid_write => grp_FFT_pipeline_DIT_fu_154_mid_write,
        revIdxTab_address0 => grp_FFT_pipeline_DIT_fu_154_revIdxTab_address0,
        revIdxTab_ce0 => grp_FFT_pipeline_DIT_fu_154_revIdxTab_ce0,
        revIdxTab_d0 => grp_FFT_pipeline_DIT_fu_154_revIdxTab_d0,
        revIdxTab_q0 => ap_const_lv7_0,
        revIdxTab_we0 => grp_FFT_pipeline_DIT_fu_154_revIdxTab_we0,
        revIdxTab_address1 => grp_FFT_pipeline_DIT_fu_154_revIdxTab_address1,
        revIdxTab_ce1 => grp_FFT_pipeline_DIT_fu_154_revIdxTab_ce1,
        revIdxTab_d1 => grp_FFT_pipeline_DIT_fu_154_revIdxTab_d1,
        revIdxTab_q1 => ap_const_lv7_0,
        revIdxTab_we1 => grp_FFT_pipeline_DIT_fu_154_revIdxTab_we1,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_FFT_pipeline_DIT_fu_154_ap_start,
        ap_done => grp_FFT_pipeline_DIT_fu_154_ap_done,
        ap_ready => grp_FFT_pipeline_DIT_fu_154_ap_ready,
        ap_idle => grp_FFT_pipeline_DIT_fu_154_ap_idle,
        ap_continue => grp_FFT_pipeline_DIT_fu_154_ap_continue);

    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251 : component FFT_DIT_RN_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start,
        ap_done => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_done,
        ap_idle => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_idle,
        ap_ready => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_ready,
        mid_dout => mid_dout,
        mid_empty_n => mid_empty_n,
        mid_read => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_mid_read,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_d0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_d0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_d0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_d0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_d0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_d0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_d0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_d0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_d0);

    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272 : component FFT_DIT_RN_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start,
        ap_done => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_done,
        ap_idle => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_idle,
        ap_ready => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_ready,
        revIdxTab_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_address0,
        revIdxTab_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_ce0,
        revIdxTab_q0 => revIdxTab_q0);

    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282 : component FFT_DIT_RN_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start,
        ap_done => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done,
        ap_idle => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_idle,
        ap_ready => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_ready,
        out_r_din => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_din,
        out_r_full_n => out_r_full_n,
        out_r_write => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_write,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_q0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_q0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_q0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_q0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_q0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_q0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_q0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 => grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0,
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_q0 => FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_q0);

    mid_fifo_U : component FFT_DIT_RN_fifo_w256_d8_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_FFT_pipeline_DIT_fu_154_mid_din,
        if_full_n => mid_full_n,
        if_write => mid_write,
        if_dout => mid_dout,
        if_empty_n => mid_empty_n,
        if_read => mid_read);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done <= ap_const_logic_0;
                elsif ((grp_FFT_pipeline_DIT_fu_154_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready <= ap_const_logic_0;
                elsif ((grp_FFT_pipeline_DIT_fu_154_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_ready = ap_const_logic_1)) then 
                    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_ready = ap_const_logic_1)) then 
                    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_ready = ap_const_logic_1)) then 
                    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_FFT_pipeline_DIT_fu_154_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_FFT_pipeline_DIT_fu_154_ap_start_reg <= ap_const_logic_0;
            else
                if ((((ap_sync_grp_FFT_pipeline_DIT_fu_154_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
                    grp_FFT_pipeline_DIT_fu_154_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FFT_pipeline_DIT_fu_154_ap_ready = ap_const_logic_1)) then 
                    grp_FFT_pipeline_DIT_fu_154_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done, ap_CS_fsm_state2, ap_block_state2_on_subcall_done, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_block_state4_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 <= "XXXXXX";
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 <= "XXXXXX";
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 <= "XXXXXX";
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 <= "XXXXXX";
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 <= "XXXXXX";
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 <= "XXXXXX";
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 <= "XXXXXX";
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 <= "XXXXXX";
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0;
        else 
            FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state4_on_subcall_done)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done)
    begin
        if ((grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready, ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready and ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done) = ap_const_logic_0);
    end process;


    ap_block_state4_on_subcall_done_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_done, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_done)
    begin
                ap_block_state4_on_subcall_done <= ((grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_done = ap_const_logic_0) or (grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_sync_grp_FFT_pipeline_DIT_fu_154_ap_ready <= (grp_FFT_pipeline_DIT_fu_154_ap_ready or ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready);
    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg;
    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg;
    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg;

    grp_FFT_pipeline_DIT_fu_154_ap_continue_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            grp_FFT_pipeline_DIT_fu_154_ap_continue <= ap_const_logic_1;
        else 
            grp_FFT_pipeline_DIT_fu_154_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_FFT_pipeline_DIT_fu_154_ap_start <= grp_FFT_pipeline_DIT_fu_154_ap_start_reg;
    in_r_read <= grp_FFT_pipeline_DIT_fu_154_in_r_read;

    mid_read_assign_proc : process(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_mid_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mid_read <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_mid_read;
        else 
            mid_read <= ap_const_logic_0;
        end if; 
    end process;


    mid_write_assign_proc : process(grp_FFT_pipeline_DIT_fu_154_mid_write, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mid_write <= grp_FFT_pipeline_DIT_fu_154_mid_write;
        else 
            mid_write <= ap_const_logic_0;
        end if; 
    end process;

    out_r_din <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_din;
    out_r_write <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_write;

    revIdxTab_address0_assign_proc : process(grp_FFT_pipeline_DIT_fu_154_revIdxTab_address0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            revIdxTab_address0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            revIdxTab_address0 <= grp_FFT_pipeline_DIT_fu_154_revIdxTab_address0;
        else 
            revIdxTab_address0 <= "XXXXXXX";
        end if; 
    end process;


    revIdxTab_ce0_assign_proc : process(grp_FFT_pipeline_DIT_fu_154_revIdxTab_ce0, grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            revIdxTab_ce0 <= grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            revIdxTab_ce0 <= grp_FFT_pipeline_DIT_fu_154_revIdxTab_ce0;
        else 
            revIdxTab_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    revIdxTab_we0_assign_proc : process(grp_FFT_pipeline_DIT_fu_154_revIdxTab_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            revIdxTab_we0 <= grp_FFT_pipeline_DIT_fu_154_revIdxTab_we0;
        else 
            revIdxTab_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
