// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FFT_DIT_RN_FFT_DIT_RN,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.091000,HLS_SYN_LAT=1258,HLS_SYN_TPT=none,HLS_SYN_MEM=123,HLS_SYN_DSP=0,HLS_SYN_FF=79998,HLS_SYN_LUT=65078,HLS_VERSION=2024_2}" *)

module FFT_DIT_RN (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_dout,
        in_r_empty_n,
        in_r_read,
        out_r_din,
        out_r_full_n,
        out_r_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [255:0] in_r_dout;
input   in_r_empty_n;
output   in_r_read;
output  [255:0] out_r_din;
input   out_r_full_n;
output   out_r_write;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [6:0] revIdxTab_address0;
reg    revIdxTab_ce0;
reg    revIdxTab_we0;
wire   [6:0] revIdxTab_q0;
reg   [5:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0;
wire   [31:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_q0;
reg   [5:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0;
wire   [31:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_q0;
reg   [5:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0;
wire   [31:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_q0;
reg   [5:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0;
wire   [31:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_q0;
reg   [5:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0;
wire   [31:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_q0;
reg   [5:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0;
wire   [31:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_q0;
reg   [5:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0;
wire   [31:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_q0;
reg   [5:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0;
reg    FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0;
wire   [31:0] FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_q0;
wire    grp_FFT_pipeline_DIT_fu_154_in_r_read;
wire   [255:0] grp_FFT_pipeline_DIT_fu_154_mid_din;
wire    grp_FFT_pipeline_DIT_fu_154_mid_write;
wire   [6:0] grp_FFT_pipeline_DIT_fu_154_revIdxTab_address0;
wire    grp_FFT_pipeline_DIT_fu_154_revIdxTab_ce0;
wire   [6:0] grp_FFT_pipeline_DIT_fu_154_revIdxTab_d0;
wire    grp_FFT_pipeline_DIT_fu_154_revIdxTab_we0;
wire   [6:0] grp_FFT_pipeline_DIT_fu_154_revIdxTab_address1;
wire    grp_FFT_pipeline_DIT_fu_154_revIdxTab_ce1;
wire   [6:0] grp_FFT_pipeline_DIT_fu_154_revIdxTab_d1;
wire    grp_FFT_pipeline_DIT_fu_154_revIdxTab_we1;
wire    grp_FFT_pipeline_DIT_fu_154_ap_start;
wire    grp_FFT_pipeline_DIT_fu_154_ap_done;
wire    grp_FFT_pipeline_DIT_fu_154_ap_ready;
wire    grp_FFT_pipeline_DIT_fu_154_ap_idle;
reg    grp_FFT_pipeline_DIT_fu_154_ap_continue;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_done;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_idle;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_ready;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_mid_read;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0;
wire   [31:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_d0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0;
wire   [31:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_d0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0;
wire   [31:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_d0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0;
wire   [31:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_d0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0;
wire   [31:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_d0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0;
wire   [31:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_d0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0;
wire   [31:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_d0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0;
wire   [31:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_d0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_done;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_idle;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_ready;
wire   [6:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_ce0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_idle;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_ready;
wire   [255:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_din;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_write;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0;
wire   [5:0] grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0;
wire    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0;
reg    grp_FFT_pipeline_DIT_fu_154_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready;
reg    ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done;
reg    ap_block_state2_on_subcall_done;
wire    ap_sync_grp_FFT_pipeline_DIT_fu_154_ap_ready;
wire    mid_full_n;
reg    mid_write;
reg    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [255:0] mid_dout;
wire    mid_empty_n;
reg    mid_read;
wire    ap_CS_fsm_state4;
reg    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg;
reg    grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_block_state4_on_subcall_done;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_FFT_pipeline_DIT_fu_154_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready = 1'b0;
#0 ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done = 1'b0;
#0 grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg = 1'b0;
#0 grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg = 1'b0;
#0 grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg = 1'b0;
end

FFT_DIT_RN_revIdxTab_RAM_AUTO_1R1W #(
    .DataWidth( 7 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
revIdxTab_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(revIdxTab_address0),
    .ce0(revIdxTab_ce0),
    .we0(revIdxTab_we0),
    .d0(grp_FFT_pipeline_DIT_fu_154_revIdxTab_d0),
    .q0(revIdxTab_q0)
);

FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0),
    .ce0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0),
    .we0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0),
    .d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_d0),
    .q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_q0)
);

FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0),
    .ce0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0),
    .we0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0),
    .d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_d0),
    .q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_q0)
);

FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0),
    .ce0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0),
    .we0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0),
    .d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_d0),
    .q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_q0)
);

FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0),
    .ce0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0),
    .we0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0),
    .d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_d0),
    .q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_q0)
);

FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0),
    .ce0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0),
    .we0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0),
    .d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_d0),
    .q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_q0)
);

FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0),
    .ce0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0),
    .we0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0),
    .d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_d0),
    .q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_q0)
);

FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0),
    .ce0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0),
    .we0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0),
    .d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_d0),
    .q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_q0)
);

FFT_DIT_RN_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_RAM_AUTO_2R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0),
    .ce0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0),
    .we0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0),
    .d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_d0),
    .q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_q0)
);

FFT_DIT_RN_FFT_pipeline_DIT grp_FFT_pipeline_DIT_fu_154(
    .in_r_dout(in_r_dout),
    .in_r_empty_n(in_r_empty_n),
    .in_r_read(grp_FFT_pipeline_DIT_fu_154_in_r_read),
    .mid_din(grp_FFT_pipeline_DIT_fu_154_mid_din),
    .mid_full_n(mid_full_n),
    .mid_write(grp_FFT_pipeline_DIT_fu_154_mid_write),
    .revIdxTab_address0(grp_FFT_pipeline_DIT_fu_154_revIdxTab_address0),
    .revIdxTab_ce0(grp_FFT_pipeline_DIT_fu_154_revIdxTab_ce0),
    .revIdxTab_d0(grp_FFT_pipeline_DIT_fu_154_revIdxTab_d0),
    .revIdxTab_q0(7'd0),
    .revIdxTab_we0(grp_FFT_pipeline_DIT_fu_154_revIdxTab_we0),
    .revIdxTab_address1(grp_FFT_pipeline_DIT_fu_154_revIdxTab_address1),
    .revIdxTab_ce1(grp_FFT_pipeline_DIT_fu_154_revIdxTab_ce1),
    .revIdxTab_d1(grp_FFT_pipeline_DIT_fu_154_revIdxTab_d1),
    .revIdxTab_q1(7'd0),
    .revIdxTab_we1(grp_FFT_pipeline_DIT_fu_154_revIdxTab_we1),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_FFT_pipeline_DIT_fu_154_ap_start),
    .ap_done(grp_FFT_pipeline_DIT_fu_154_ap_done),
    .ap_ready(grp_FFT_pipeline_DIT_fu_154_ap_ready),
    .ap_idle(grp_FFT_pipeline_DIT_fu_154_ap_idle),
    .ap_continue(grp_FFT_pipeline_DIT_fu_154_ap_continue)
);

FFT_DIT_RN_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1 grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start),
    .ap_done(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_done),
    .ap_idle(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_idle),
    .ap_ready(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_ready),
    .mid_dout(mid_dout),
    .mid_empty_n(mid_empty_n),
    .mid_read(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_mid_read),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_d0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_d0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_d0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_d0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_d0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_d0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_d0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_d0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_d0)
);

FFT_DIT_RN_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1 grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start),
    .ap_done(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_done),
    .ap_idle(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_idle),
    .ap_ready(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_ready),
    .revIdxTab_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_address0),
    .revIdxTab_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_ce0),
    .revIdxTab_q0(revIdxTab_q0)
);

FFT_DIT_RN_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2 grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start),
    .ap_done(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done),
    .ap_idle(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_idle),
    .ap_ready(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_ready),
    .out_r_din(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_din),
    .out_r_full_n(out_r_full_n),
    .out_r_write(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_write),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_q0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_q0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_q0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_q0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_q0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_q0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_q0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0(grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0),
    .FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_q0(FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_q0)
);

FFT_DIT_RN_fifo_w256_d8_A mid_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_FFT_pipeline_DIT_fu_154_mid_din),
    .if_full_n(mid_full_n),
    .if_write(mid_write),
    .if_dout(mid_dout),
    .if_empty_n(mid_empty_n),
    .if_read(mid_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done <= 1'b0;
        end else if ((grp_FFT_pipeline_DIT_fu_154_ap_done == 1'b1)) begin
            ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready <= 1'b0;
        end else if ((grp_FFT_pipeline_DIT_fu_154_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg <= 1'b1;
        end else if ((grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_ready == 1'b1)) begin
            grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg <= 1'b1;
        end else if ((grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_ready == 1'b1)) begin
            grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg <= 1'b1;
        end else if ((grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_ready == 1'b1)) begin
            grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_FFT_pipeline_DIT_fu_154_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_sync_grp_FFT_pipeline_DIT_fu_154_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
            grp_FFT_pipeline_DIT_fu_154_ap_start_reg <= 1'b1;
        end else if ((grp_FFT_pipeline_DIT_fu_154_ap_ready == 1'b1)) begin
            grp_FFT_pipeline_DIT_fu_154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_0_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0;
    end else begin
        FFT_DIT_RN_stream_stream_vector_complex_float_4ul_0_buffer_1_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_FFT_pipeline_DIT_fu_154_ap_continue = 1'b1;
    end else begin
        grp_FFT_pipeline_DIT_fu_154_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mid_read = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_mid_read;
    end else begin
        mid_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mid_write = grp_FFT_pipeline_DIT_fu_154_mid_write;
    end else begin
        mid_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        revIdxTab_address0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        revIdxTab_address0 = grp_FFT_pipeline_DIT_fu_154_revIdxTab_address0;
    end else begin
        revIdxTab_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        revIdxTab_ce0 = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_revIdxTab_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        revIdxTab_ce0 = grp_FFT_pipeline_DIT_fu_154_revIdxTab_ce0;
    end else begin
        revIdxTab_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        revIdxTab_we0 = grp_FFT_pipeline_DIT_fu_154_revIdxTab_we0;
    end else begin
        revIdxTab_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready & ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_done) == 1'b0);
end

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_done == 1'b0) | (grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_done == 1'b0));
end

assign ap_sync_grp_FFT_pipeline_DIT_fu_154_ap_ready = (grp_FFT_pipeline_DIT_fu_154_ap_ready | ap_sync_reg_grp_FFT_pipeline_DIT_fu_154_ap_ready);

assign grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_734_1_fu_272_ap_start_reg;

assign grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_757_1_fu_251_ap_start_reg;

assign grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_ap_start_reg;

assign grp_FFT_pipeline_DIT_fu_154_ap_start = grp_FFT_pipeline_DIT_fu_154_ap_start_reg;

assign in_r_read = grp_FFT_pipeline_DIT_fu_154_in_r_read;

assign out_r_din = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_din;

assign out_r_write = grp_FFT_DIT_RN_Pipeline_VITIS_LOOP_764_2_fu_282_out_r_write;

endmodule //FFT_DIT_RN
