-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FFT_DIT_RN_FFT_pipeline_DIT is
port (
    in_r_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    in_r_empty_n : IN STD_LOGIC;
    in_r_read : OUT STD_LOGIC;
    mid_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    mid_full_n : IN STD_LOGIC;
    mid_write : OUT STD_LOGIC;
    revIdxTab_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    revIdxTab_ce0 : OUT STD_LOGIC;
    revIdxTab_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    revIdxTab_q0 : IN STD_LOGIC_VECTOR (6 downto 0);
    revIdxTab_we0 : OUT STD_LOGIC;
    revIdxTab_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    revIdxTab_ce1 : OUT STD_LOGIC;
    revIdxTab_d1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    revIdxTab_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    revIdxTab_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of FFT_DIT_RN_FFT_pipeline_DIT is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_start : STD_LOGIC;
    signal FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_done : STD_LOGIC;
    signal FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_continue : STD_LOGIC;
    signal FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_idle : STD_LOGIC;
    signal FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready : STD_LOGIC;
    signal FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_ce0 : STD_LOGIC;
    signal FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_we0 : STD_LOGIC;
    signal FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_d0 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal FFT_DIT_spatial_unroll_CY_stream_vector_U0_in_r_read : STD_LOGIC;
    signal FFT_DIT_spatial_unroll_CY_stream_vector_U0_mid_din : STD_LOGIC_VECTOR (255 downto 0);
    signal FFT_DIT_spatial_unroll_CY_stream_vector_U0_mid_write : STD_LOGIC;
    signal FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_start : STD_LOGIC;
    signal FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_done : STD_LOGIC;
    signal FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready : STD_LOGIC;
    signal FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_idle : STD_LOGIC;
    signal FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_continue : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component FFT_DIT_RN_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        revIdxTab_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        revIdxTab_ce0 : OUT STD_LOGIC;
        revIdxTab_we0 : OUT STD_LOGIC;
        revIdxTab_d0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component FFT_DIT_RN_FFT_DIT_spatial_unroll_CY_stream_vector IS
    port (
        in_r_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        in_r_empty_n : IN STD_LOGIC;
        in_r_read : OUT STD_LOGIC;
        mid_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        mid_full_n : IN STD_LOGIC;
        mid_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0 : component FFT_DIT_RN_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_start,
        ap_done => FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_done,
        ap_continue => FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_continue,
        ap_idle => FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_idle,
        ap_ready => FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready,
        revIdxTab_address0 => FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_address0,
        revIdxTab_ce0 => FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_ce0,
        revIdxTab_we0 => FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_we0,
        revIdxTab_d0 => FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_d0);

    FFT_DIT_spatial_unroll_CY_stream_vector_U0 : component FFT_DIT_RN_FFT_DIT_spatial_unroll_CY_stream_vector
    port map (
        in_r_dout => in_r_dout,
        in_r_empty_n => in_r_empty_n,
        in_r_read => FFT_DIT_spatial_unroll_CY_stream_vector_U0_in_r_read,
        mid_din => FFT_DIT_spatial_unroll_CY_stream_vector_U0_mid_din,
        mid_full_n => mid_full_n,
        mid_write => FFT_DIT_spatial_unroll_CY_stream_vector_U0_mid_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_start,
        ap_done => FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_done,
        ap_ready => FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready,
        ap_idle => FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_idle,
        ap_continue => FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_continue);





    ap_sync_reg_FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready <= ap_sync_FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready <= ap_sync_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_continue <= ap_sync_continue;
    FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_start <= ((ap_sync_reg_FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready xor ap_const_logic_1) and ap_start);
    FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_continue <= ap_sync_continue;
    FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_start <= ((ap_sync_reg_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    ap_done <= ap_sync_done;
    ap_idle <= (FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_idle and FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready <= (ap_sync_reg_FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready or FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready);
    ap_sync_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready <= (ap_sync_reg_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready or FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready);
    ap_sync_continue <= (ap_sync_done and ap_continue);
    ap_sync_done <= (FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_done and FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_done);
    ap_sync_ready <= (ap_sync_FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_ap_ready and ap_sync_FFT_DIT_spatial_unroll_CY_stream_vector_U0_ap_ready);
    in_r_read <= FFT_DIT_spatial_unroll_CY_stream_vector_U0_in_r_read;
    mid_din <= FFT_DIT_spatial_unroll_CY_stream_vector_U0_mid_din;
    mid_write <= FFT_DIT_spatial_unroll_CY_stream_vector_U0_mid_write;
    revIdxTab_address0 <= FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_address0;
    revIdxTab_address1 <= ap_const_lv7_0;
    revIdxTab_ce0 <= FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_ce0;
    revIdxTab_ce1 <= ap_const_logic_0;
    revIdxTab_d0 <= FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_d0;
    revIdxTab_d1 <= ap_const_lv7_0;
    revIdxTab_we0 <= FFT_pipeline_DIT_Loop_LOOP_REVIDTAB_proc_U0_revIdxTab_we0;
    revIdxTab_we1 <= ap_const_logic_0;
end behav;
